### ISSUE TITLE
See if we can peak at a socket

### ISSUE THREAD

**Issue by daniel-sudz** [olincollege/p2p-networking#13]
Epoll is configured in two modes: https://man7.org/linux/man-pages/man7/epoll.7.html
edge triggering -> trigger once on new data must consume immediately 
level trigger -> trigger forever until data has been read in by the user

A potential issue is if a message does not arrive in one piece which could pose a problem because it's not clear what to do with half a message.

Idea: Try to "peak" at the message in level triggered mode to determine if we have an entire message. Do nothing if we have a partial message (let epoll trigger again later) or process data from the socket if we do.

**Comment by daniel-sudz** [comment]
message peak workflow: https://pubs.opengroup.org/onlinepubs/007904975/functions/recv.html

**Comment by daniel-sudz** [comment]
peaking should be possible with `MSG_PEEK` flag to the read command from a socket. For this issue, implement a generic function based maybe like this: 

```
int full_message_availiable(int socket) 
```

**Comment by BenjiPugh** [comment]
Alright, first pass implemented. If I did it correctly, it was easier than I thought it might be. I used an int buffer for ease but let me know if it makes more sense otherwise.

**Comment by BenjiPugh** [comment]
Alright, completed a first pass on the "Peeking". I used an int buffer for ease of reading the length of the message, but let me know if it would be better to do differently.

**Comment by daniel-sudz** [comment]
solved in https://github.com/olincollege/p2p-networking/pull/21
