### ISSUE TITLE
figure out how to initialize the pieces that we have and want

### ISSUE THREAD

**Issue by daniel-sudz** [olincollege/p2p-networking#22]
it was suggested to use standard in to specify the pieces that our client has. We also need to somehow initialize the pieces that we want. These should be read into some kind of structure (using our hashmap implementation would probably be the way to go to make this scalable).

**Comment by daniel-sudz** [comment]
some kind of documentation about the format would be great along with unit tests. This can probably be done in a standalone file to not clobber up the loop.c with more helper functions.

**Comment by daniel-sudz** [comment]
I was thinking of a structure to called `struct client_state` in `state.c` which would contain a hash map for `pieces_have`, `pieces_want `, `clients_connected_file_descriptors`, `clients_connected_port_numbers`.

**Comment by BenjiPugh** [comment]
For pieces have, would these be a hash table with the key value pair of sha256 hash, data?
